const empty={clients:[],ingredients:[],products:[],sizes:[],components:[],orders:[],expenses:[],movements:[],demoRecipes:false};
export function registerCoreRoutes(app,pool,hasDatabase){
  app.get('/api/health',(req,res)=>res.json({ok:true,database:hasDatabase}));
  app.get('/api/bootstrap',async(req,res,next)=>{try{
    if(!pool)return res.json(empty);
    const [clients,ingredients,products,sizes,components,orders,items,expenses,movements,recipes,meta]=await Promise.all([
      pool.query('SELECT * FROM clients ORDER BY name'),pool.query('SELECT * FROM ingredients WHERE active=TRUE ORDER BY name'),pool.query('SELECT * FROM products WHERE active=TRUE ORDER BY category,name'),pool.query('SELECT * FROM sizes WHERE active=TRUE ORDER BY id'),pool.query('SELECT * FROM components WHERE active=TRUE ORDER BY component_group,name'),pool.query('SELECT * FROM orders ORDER BY pickup_date,pickup_time'),pool.query('SELECT * FROM order_items ORDER BY id'),pool.query('SELECT * FROM expenses ORDER BY expense_date DESC,id DESC'),pool.query('SELECT * FROM stock_movements ORDER BY created_at DESC LIMIT 100'),pool.query('SELECT * FROM component_ingredients ORDER BY component_id,ingredient_id'),pool.query("SELECT value FROM app_meta WHERE key='recipes_demo'")]);
    const comps=components.rows.map(c=>({...c,recipe:recipes.rows.filter(r=>Number(r.component_id)===Number(c.id))}));
    const ords=orders.rows.map(o=>({...o,items:items.rows.filter(i=>Number(i.order_id)===Number(o.id))}));
    res.json({clients:clients.rows,ingredients:ingredients.rows,products:products.rows,sizes:sizes.rows,components:comps,orders:ords,expenses:expenses.rows,movements:movements.rows,demoRecipes:meta.rows[0]?.value==='true'});
  }catch(e){next(e)}});

  const needDb=res=>{if(!pool){res.status(503).json({error:'Base de dados não configurada'});return true}return false};
  app.post('/api/clients',async(req,res,next)=>{try{if(needDb(res))return;const name=String(req.body.name||'').trim(),contact=String(req.body.contact||'').trim();if(!name)return res.status(400).json({error:'Nome obrigatório'});if(contact){const d=await pool.query('SELECT name FROM clients WHERE contact=$1 LIMIT 1',[contact]);if(d.rows[0])return res.status(409).json({error:`Já existe um cliente com este contacto: ${d.rows[0].name}`})}const {rows}=await pool.query('INSERT INTO clients(name,contact) VALUES($1,$2) RETURNING *',[name,contact||null]);res.json(rows[0])}catch(e){next(e)}});
  app.put('/api/clients/:id',async(req,res,next)=>{try{if(needDb(res))return;const id=+req.params.id,name=String(req.body.name||'').trim(),contact=String(req.body.contact||'').trim();if(contact){const d=await pool.query('SELECT name FROM clients WHERE contact=$1 AND id<>$2 LIMIT 1',[contact,id]);if(d.rows[0])return res.status(409).json({error:`Já existe um cliente com este contacto: ${d.rows[0].name}`})}const {rows}=await pool.query('UPDATE clients SET name=$1,contact=$2 WHERE id=$3 RETURNING *',[name,contact||null,id]);res.json(rows[0])}catch(e){next(e)}});

  app.post('/api/products',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('INSERT INTO products(name,category,price,pricing_type) VALUES($1,$2,$3,$4) RETURNING *',[b.name,b.category||null,b.price||0,b.pricing_type||'unidade']);res.json(rows[0])}catch(e){next(e)}});
  app.put('/api/products/:id',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('UPDATE products SET name=$1,category=$2,price=$3,pricing_type=$4 WHERE id=$5 RETURNING *',[b.name,b.category||null,b.price||0,b.pricing_type||'unidade',+req.params.id]);res.json(rows[0])}catch(e){next(e)}});
  app.post('/api/sizes',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('INSERT INTO sizes(name,cake_weight,cover_weight) VALUES($1,$2,$3) RETURNING *',[b.name,b.cake_weight||0,b.cover_weight||0]);res.json(rows[0])}catch(e){next(e)}});
  app.put('/api/sizes/:id',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('UPDATE sizes SET name=$1,cake_weight=$2,cover_weight=$3 WHERE id=$4 RETURNING *',[b.name,b.cake_weight||0,b.cover_weight||0,+req.params.id]);res.json(rows[0])}catch(e){next(e)}});
  app.post('/api/ingredients',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('INSERT INTO ingredients(name,unit,stock,min_stock,ideal_stock) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.name,b.unit||'g',b.stock||0,b.min_stock||0,b.ideal_stock||null]);res.json(rows[0])}catch(e){next(e)}});
  app.put('/api/ingredients/:id',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('UPDATE ingredients SET name=$1,unit=$2,min_stock=$3,ideal_stock=$4 WHERE id=$5 RETURNING *',[b.name,b.unit||'g',b.min_stock||0,b.ideal_stock||null,+req.params.id]);res.json(rows[0])}catch(e){next(e)}});

  async function saveComponent(req,res,next,id=null){try{if(needDb(res))return;const b=req.body,c=await pool.connect();try{await c.query('BEGIN');let row;if(id)row=(await c.query('UPDATE components SET name=$1,component_group=$2,reference_weight=$3,is_demo=$4 WHERE id=$5 RETURNING *',[b.name,b.component_group,b.reference_weight||0,!!b.is_demo,id])).rows[0];else{row=(await c.query('INSERT INTO components(name,component_group,reference_weight,is_demo) VALUES($1,$2,$3,$4) RETURNING *',[b.name,b.component_group,b.reference_weight||0,!!b.is_demo])).rows[0];id=row.id}await c.query('DELETE FROM component_ingredients WHERE component_id=$1',[id]);for(const r of b.recipe||[])await c.query('INSERT INTO component_ingredients(component_id,ingredient_id,quantity) VALUES($1,$2,$3)',[id,r.ingredient_id,r.quantity||0]);await c.query('COMMIT');res.json({...row,recipe:b.recipe||[]})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}}
  app.post('/api/components',(req,res,next)=>saveComponent(req,res,next));
  app.put('/api/components/:id',(req,res,next)=>saveComponent(req,res,next,+req.params.id));

  app.post('/api/stock-movements',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,id=+b.ingredient_id,type=b.movement_type||'Entrada',qty=Math.abs(+b.quantity||0),cost=+b.cost||0;if(!qty)return res.status(400).json({error:'Quantidade inválida'});const c=await pool.connect();try{await c.query('BEGIN');await c.query(`UPDATE ingredients SET stock=stock ${type==='Entrada'?'+':'-'} $1 WHERE id=$2`,[qty,id]);const {rows}=await c.query('INSERT INTO stock_movements(ingredient_id,movement_type,quantity,cost,note) VALUES($1,$2,$3,$4,$5) RETURNING *',[id,type,qty,cost,b.note||null]);if(cost>0){const ing=await c.query('SELECT name FROM ingredients WHERE id=$1',[id]);await c.query("INSERT INTO expenses(name,expense_type,value,expense_date) VALUES($1,'Pontual',$2,CURRENT_DATE)",[ `Reposição de stock — ${ing.rows[0]?.name||'Ingrediente'}`,cost])}await c.query('COMMIT');res.json(rows[0])}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});

  app.post('/api/expenses',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('INSERT INTO expenses(name,expense_type,value,expense_date) VALUES($1,$2,$3,$4) RETURNING *',[b.name,b.expense_type,b.value,b.expense_date]);res.json(rows[0])}catch(e){next(e)}});
  app.put('/api/expenses/:id',async(req,res,next)=>{try{if(needDb(res))return;const b=req.body,{rows}=await pool.query('UPDATE expenses SET name=$1,expense_type=$2,value=$3,expense_date=$4 WHERE id=$5 RETURNING *',[b.name,b.expense_type,b.value,b.expense_date,+req.params.id]);res.json(rows[0])}catch(e){next(e)}});

  app.delete('/api/:type/:id',async(req,res,next)=>{try{if(needDb(res))return;const id=+req.params.id,type=req.params.type,cfg={products:['products',1],components:['components',1],sizes:['sizes',1],expenses:['expenses',0],clients:['clients',0]}[type];if(!cfg)return res.status(404).json({error:'Tipo inválido'});if(type==='clients'){const used=await pool.query('SELECT 1 FROM orders WHERE client_id=$1 LIMIT 1',[id]);if(used.rows[0])return res.status(409).json({error:'Este cliente tem histórico de encomendas e não pode ser apagado.'})}if(cfg[1])await pool.query(`UPDATE ${cfg[0]} SET active=FALSE WHERE id=$1`,[id]);else await pool.query(`DELETE FROM ${cfg[0]} WHERE id=$1`,[id]);res.json({ok:true})}catch(e){next(e)}});
  app.post('/api/admin/reset-recipes',async(req,res,next)=>{try{if(needDb(res))return;const c=await pool.connect();try{await c.query('BEGIN');await c.query('DELETE FROM component_ingredients');await c.query('UPDATE components SET reference_weight=0,is_demo=FALSE');await c.query("INSERT INTO app_meta(key,value) VALUES('recipes_demo','false') ON CONFLICT(key) DO UPDATE SET value='false'");await c.query('COMMIT');res.json({ok:true})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});
}
