export function registerOrderRoutes(app,pool){
  const needDb=res=>{if(!pool){res.status(503).json({error:'Base de dados não configurada'});return true}return false};
  async function saveOrder(req,res,next,id=null){try{if(needDb(res))return;const b=req.body,c=await pool.connect();try{await c.query('BEGIN');let row;if(id){const old=await c.query('SELECT stock_applied FROM orders WHERE id=$1',[id]);if(old.rows[0]?.stock_applied){await c.query('ROLLBACK');return res.status(409).json({error:'Encomenda já preparada: edições exigem reconciliação de stock.'})}row=(await c.query('UPDATE orders SET client_id=$1,pickup_date=$2,pickup_time=$3,original_total=$4,discount_type=$5,discount_value=$6,final_total=$7 WHERE id=$8 RETURNING *',[b.client_id,b.pickup_date,b.pickup_time||null,b.original_total||0,b.discount_type||'none',b.discount_value||0,b.final_total||0,id])).rows[0];await c.query('DELETE FROM order_items WHERE order_id=$1',[id])}else{row=(await c.query("INSERT INTO orders(client_id,pickup_date,pickup_time,status,original_total,discount_type,discount_value,final_total,stock_applied) VALUES($1,$2,$3,'Registada',$4,$5,$6,$7,FALSE) RETURNING *",[b.client_id,b.pickup_date,b.pickup_time||null,b.original_total||0,b.discount_type||'none',b.discount_value||0,b.final_total||0])).rows[0];id=row.id}for(const it of b.items||[])await c.query('INSERT INTO order_items(order_id,item_type,product_id,base_component_id,cover_component_id,size_id,quantity,unit_price,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,it.item_type,it.product_id||null,it.base_component_id||null,it.cover_component_id||null,it.size_id||null,it.quantity||1,it.unit_price||0,JSON.stringify(it.snapshot||{})]);await c.query('COMMIT');res.json(row)}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}}
  app.post('/api/orders',(req,res,next)=>saveOrder(req,res,next));
  app.put('/api/orders/:id',(req,res,next)=>saveOrder(req,res,next,+req.params.id));

  app.post('/api/orders/:id/prepare',async(req,res,next)=>{try{if(needDb(res))return;const id=+req.params.id,actual=req.body.actual||[],apply=req.body.apply_stock!==false,c=await pool.connect();try{await c.query('BEGIN');const old=await c.query('SELECT stock_applied FROM orders WHERE id=$1 FOR UPDATE',[id]);if(old.rows[0]?.stock_applied){await c.query('ROLLBACK');return res.status(409).json({error:'O stock desta encomenda já foi aplicado.'})}await c.query('DELETE FROM order_consumption WHERE order_id=$1',[id]);for(const r of actual){const ing=await c.query('SELECT unit FROM ingredients WHERE id=$1',[r.ingredient_id]);await c.query('INSERT INTO order_consumption(order_id,ingredient_id,predicted_qty,actual_qty,unit) VALUES($1,$2,$3,$4,$5)',[id,r.ingredient_id,r.predicted_qty??r.quantity,r.quantity,ing.rows[0]?.unit||'g']);if(apply){await c.query('UPDATE ingredients SET stock=stock-$1 WHERE id=$2',[r.quantity,r.ingredient_id]);await c.query("INSERT INTO stock_movements(ingredient_id,movement_type,quantity,note,order_id) VALUES($1,'Saída',$2,$3,$4)",[r.ingredient_id,r.quantity,`Encomenda ${id}`,id])}}const {rows}=await c.query("UPDATE orders SET status='Aguarda recolha',stock_applied=$2 WHERE id=$1 RETURNING *",[id,apply]);await c.query('COMMIT');res.json(rows[0])}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});
  app.post('/api/orders/:id/collect',async(req,res,next)=>{try{if(needDb(res))return;const {rows}=await pool.query("UPDATE orders SET status='Concluída' WHERE id=$1 RETURNING *",[+req.params.id]);res.json(rows[0])}catch(e){next(e)}});
  app.post('/api/orders/:id/cancel',async(req,res,next)=>{try{if(needDb(res))return;const id=+req.params.id,restore=!!req.body.restore_stock,c=await pool.connect();try{await c.query('BEGIN');if(restore){const cons=await c.query('SELECT ingredient_id,actual_qty FROM order_consumption WHERE order_id=$1',[id]);for(const r of cons.rows){await c.query('UPDATE ingredients SET stock=stock+$1 WHERE id=$2',[r.actual_qty,r.ingredient_id]);await c.query("INSERT INTO stock_movements(ingredient_id,movement_type,quantity,note,order_id) VALUES($1,'Entrada',$2,'Reposição por cancelamento',$3)",[r.ingredient_id,r.actual_qty,id])}}const {rows}=await c.query("UPDATE orders SET status='Cancelada' WHERE id=$1 RETURNING *",[id]);await c.query('COMMIT');res.json(rows[0])}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});
}
